import Header from '../Header';
import Head from 'next/head';
import Footer from '../Footer';
const Layout = (props) => {
  const { children, title } = props;
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
};

export default Layout;
